name: Bot Ofertas ML

on:
  schedule:
    - cron: "*/15 * * * *"  # Ejecuta cada 15 minutos
  workflow_dispatch:         # Permite ejecución manual

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Print UTC time   # <-- debug
        run: date -u

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml python-telegram-bot==13.15

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python mlbot/of_ml.py


